name: CVE Scanning

on:
  push:

jobs:
  dotnet-modules-scan:
    name: dotnet-scan
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build project with dotnet
        run: dotnet build --configuration Release
        working-directory: fdc3-dotnet
      - name: List vulnerable libraries
        run: dotnet list package --vulnerable --include-transitive
        working-directory: 'fdc3-dotnet'
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@1b5d19fd4a32ff0ff982e8c9d8e27dbf7ac8a46c
        id: Depcheck
        with:
          project: '.'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --suppression ./cve/allow-list.xml
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Depcheck report
          path: ${{ github.workspace }}/reports
